import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"  # for mac

import argparse
from pathlib import Path

import numpy as np
import torch
import yaml
from stable_baselines3 import PPO

# Resolve everything relative to this script so export does not depend on the
# current working directory (matches train.py / export_onnx.py).
SCRIPT_DIR = Path(__file__).parent
CONFIG_PATH = SCRIPT_DIR / "config.yaml"

# Kept in sync with env.DroneLevitationEnv and export_onnx.py.
OBS_DIM = 6    # [height, vz, roll, pitch, roll_rate, pitch_rate]
ACTION_DIM = 4  # [m1, m2, m3, m4]

# Default header destination: next to the firmware that consumes it.
DEFAULT_HEADER = (
    SCRIPT_DIR.parent / "firmware" / "bringup" / "imu_read" / "src" / "policy_weights.h"
)


def load_default_model_path():
    # Same default as export_onnx.py: models/<training.stage>/best.
    with open(CONFIG_PATH) as f:
        config = yaml.safe_load(f) or {}
    stage = config.get("training", {}).get("stage", "stage1")
    return f"models/{stage}/best"


def deterministic_action(policy, obs):
    # The deployed action is the Gaussian MEAN (deterministic), then clamped to
    # the Box(0,1) action range — identical to export_onnx.DeterministicActor.
    with torch.no_grad():
        action = policy._predict(obs, deterministic=True)
        return torch.clamp(action, 0.0, 1.0)


def extract_layers(policy):
    """Pull the 3 Linear layers of the pi-branch MLP from the SB3 policy.

    Introspects module names rather than hardcoding state_dict indices, so a
    layout change on an SB3 upgrade raises here instead of silently exporting
    garbage. Returns a list of (name, W[out,in], b[out]) in forward order.
    """
    net = policy.mlp_extractor.policy_net   # Sequential(Linear, Tanh, Linear, Tanh)
    linears = [m for m in net if isinstance(m, torch.nn.Linear)]
    if len(linears) != 2:
        raise RuntimeError(
            f"expected 2 Linear layers in mlp_extractor.policy_net, got {len(linears)}; "
            "SB3 net layout changed — re-check before exporting."
        )

    layers = []
    for i, lin in enumerate(linears):
        layers.append((f"policy_net.{i}", lin.weight.detach().cpu().numpy(),
                       lin.bias.detach().cpu().numpy()))

    action_net = policy.action_net          # Linear(64 -> 4), outputs the mean
    if not isinstance(action_net, torch.nn.Linear):
        raise RuntimeError(f"expected policy.action_net to be Linear, got {type(action_net)}")
    layers.append(("action_net", action_net.weight.detach().cpu().numpy(),
                   action_net.bias.detach().cpu().numpy()))

    # Shape sanity: 6->64, 64->64, 64->4.
    shapes = [w.shape for _, w, _ in layers]
    expected = [(64, OBS_DIM), (64, 64), (ACTION_DIM, 64)]
    if shapes != expected:
        raise RuntimeError(f"unexpected layer shapes {shapes}, expected {expected}")
    return layers


def _fmt_float(v):
    # %.9g round-trips float32 compactly, but emits "0"/"1" for integer-valued
    # floats — and "0f" is an invalid C octal constant. Ensure a '.' or exponent
    # is present so the 'f' suffix always attaches to a valid float literal.
    s = f"{v:.9g}"
    if not any(c in s for c in ".eEnN"):   # no dot, exponent, or inf/nan
        s += ".0"
    return s + "f"


def _fmt_array(values):
    return ", ".join(_fmt_float(v) for v in values)


def _emit_matrix(name, W):
    out, inp = W.shape
    rows = ",\n\t".join("{" + _fmt_array(W[o]) + "}" for o in range(out))
    return f"static const float {name}[{out}][{inp}] = {{\n\t{rows}\n}};\n"


def _emit_vector(name, b):
    return f"static const float {name}[{len(b)}] = {{{_fmt_array(b)}}};\n"


def write_header(layers, ref_obs, ref_action, header_path):
    (w0, b0) = (layers[0][1], layers[0][2])
    (w2, b2) = (layers[1][1], layers[1][2])
    (wa, ba) = (layers[2][1], layers[2][2])

    parts = []
    parts.append("// AUTO-GENERATED by training/export_weights.py — do not edit by hand.")
    parts.append("// SB3 PPO MlpPolicy pi-branch: 6 -> 64 -> 64 -> 4, tanh, action clamped [0,1].")
    parts.append("#ifndef POLICY_WEIGHTS_H")
    parts.append("#define POLICY_WEIGHTS_H\n")
    parts.append(f"#define POLICY_OBS_DIM {OBS_DIM}")
    parts.append(f"#define POLICY_ACT_DIM {ACTION_DIM}")
    parts.append(f"#define POLICY_H1 {w0.shape[0]}")
    parts.append(f"#define POLICY_H2 {w2.shape[0]}\n")

    parts.append("// Layer 0: Linear 6->64  (W[out][in], forward: y[o] = sum_i W[o][i]*x[i] + b[o])")
    parts.append(_emit_matrix("POLICY_W0", w0))
    parts.append(_emit_vector("POLICY_B0", b0))
    parts.append("// Layer 1: Linear 64->64")
    parts.append(_emit_matrix("POLICY_W2", w2))
    parts.append(_emit_vector("POLICY_B2", b2))
    parts.append("// action_net: Linear 64->4 (Gaussian mean)")
    parts.append(_emit_matrix("POLICY_WA", wa))
    parts.append(_emit_vector("POLICY_BA", ba))

    parts.append("// Reference (obs -> action) pair for the firmware boot self-check.")
    parts.append(_emit_vector("POLICY_REF_OBS", ref_obs))
    parts.append(_emit_vector("POLICY_REF_ACTION", ref_action))

    parts.append("\n#endif  // POLICY_WEIGHTS_H")

    header_path.parent.mkdir(parents=True, exist_ok=True)
    header_path.write_text("\n".join(parts) + "\n")


def export(model_path=None, header_path=None):
    if model_path is None:
        model_path = SCRIPT_DIR / load_default_model_path()
    if header_path is None:
        header_path = DEFAULT_HEADER

    model = PPO.load(str(model_path), device="cpu")
    policy = model.policy
    policy.eval()

    layers = extract_layers(policy)

    # Realistic-magnitude reference obs (not zeros, which can sit at a degenerate
    # point): height~0.5m, vz~0.3, roll/pitch~±0.2rad, rates~±0.4rad/s.
    ref_obs = np.array([0.5, 0.3, 0.2, -0.2, 0.4, -0.3], dtype=np.float32)
    ref_obs_t = torch.tensor(ref_obs.reshape(1, OBS_DIM))
    ref_action = deterministic_action(policy, ref_obs_t).numpy().reshape(ACTION_DIM)

    write_header(layers, ref_obs, ref_action, Path(header_path))

    print(f"wrote weights header -> {header_path}")
    print(f"  layers: 6->64, 64->64, 64->4  (tanh, clamp[0,1])")
    print(f"  ref obs    : {ref_obs.tolist()}")
    print(f"  ref action : {[round(float(a), 6) for a in ref_action]}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Extract a trained PPO policy's weights to a C header for on-MCU inference"
    )
    parser.add_argument(
        "--model", type=str, default=None,
        help="path to the trained model .zip (defaults to models/<training.stage>/best)",
    )
    parser.add_argument(
        "--out", type=str, default=None,
        help=f"output .h path (defaults to {DEFAULT_HEADER})",
    )
    args = parser.parse_args()
    export(model_path=args.model,
           header_path=Path(args.out) if args.out else None)
