// On-CPU inference for the PPO MLP policy (6 -> 64 -> 64 -> 4, tanh, clamp[0,1]).
// Weights live in policy_weights.h, generated by training/export_weights.py.
#ifndef POLICY_H
#define POLICY_H

// Run one forward pass: obs[6] -> action[4]. Outputs are clamped to [0,1],
void policy_forward(const float obs[6], float action[4]);

// Check policy_forward against the reference (obs, action) in policy_weights.h.
// Returns 0 if all outputs are within tolerance, else -1; writes max abs error
// to *max_error if non-NULL.
int policy_self_check(float tolerance, float *max_error);

#endif  // POLICY_H
