// On-CPU inference for the PPO MLP policy (6 -> 64 -> 64 -> 4, tanh, clamp[0,1]).
// Weights live in policy_weights.h, generated by training/export_weights.py.
#ifndef POLICY_H
#define POLICY_H

// Run one forward pass: obs[6] -> action[4]. Outputs are clamped to [0,1],
// matching the training-time action clip and the ONNX export's baked-in clamp.
void policy_forward(const float obs[6], float action[4]);

#endif  // POLICY_H
